"""Poetry is one pinned build input, not an ambient workstation tool.

The lockfile, CI bootstrap and production image must be produced by the exact
Poetry release declared by the repository.  Otherwise each surface may resolve
or normalise a different dependency graph while all of them appear healthy in
isolation.
"""

from __future__ import annotations

import tomllib
from collections.abc import Callable
from pathlib import Path

import pytest
from scripts.check_poetry_toolchain import (
    PoetryToolchainError,
    active_version,
    bootstrap_version,
    lock_generator_version,
    require_match,
    required_version,
)

REPO = Path(__file__).resolve().parents[2]
PYPROJECT = REPO / "pyproject.toml"
LOCK = REPO / "poetry.lock"
BOOTSTRAP = REPO / ".github" / "bootstrap"
ACTION = REPO / ".github" / "actions" / "setup-poetry" / "action.yml"
DOCKERFILE = REPO / "Dockerfile"
DOCKERIGNORE = REPO / ".dockerignore"
MAKEFILE = REPO / "Makefile"
WORKFLOWS = REPO / ".github" / "workflows"


def test_every_poetry_surface_uses_the_project_pin() -> None:
    wanted = required_version(PYPROJECT.read_text(encoding="utf-8"))
    assert wanted == lock_generator_version(LOCK.read_text(encoding="utf-8"))

    locks = sorted(BOOTSTRAP.glob("poetry-requirements-py*.txt"))
    assert locks, "the Poetry bootstrap has no hash-locked requirements"
    for lock in locks:
        assert bootstrap_version(lock.read_text(encoding="utf-8")) == wanted


@pytest.mark.parametrize(
    ("reader", "bad"),
    [
        (required_version, '[tool.poetry]\nrequires-poetry = ">=2.4"\n'),
        (lock_generator_version, "# generated by something else\n"),
        (bootstrap_version, "poetry==2.4.1\npoetry==2.3.1\n"),
    ],
)
def test_ambiguous_or_missing_versions_fail_closed(
    reader: Callable[[str], str], bad: str
) -> None:
    with pytest.raises(PoetryToolchainError):
        reader(bad)


def test_version_mismatch_is_visible_before_dependency_work() -> None:
    assert active_version("Poetry (version 2.4.1)") == "2.4.1"
    with pytest.raises(PoetryToolchainError, match="active Poetry uses Poetry 2.3.1"):
        require_match("2.4.1", "2.3.1", "active Poetry")


def test_ci_and_docker_verify_the_pin_on_both_sides_of_install() -> None:
    action = ACTION.read_text(encoding="utf-8")
    dockerfile = DOCKERFILE.read_text(encoding="utf-8")
    dockerignore = DOCKERIGNORE.read_text(encoding="utf-8")

    assert action.count("scripts/check_poetry_toolchain.py") >= 2
    assert "--active" in action
    assert 'poetry" check --lock' in action
    assert "ARG POETRY_VERSION" not in dockerfile
    assert "poetry-requirements-py312.txt" in dockerfile
    assert "!.github/bootstrap/" in dockerignore
    assert "!.github/bootstrap/poetry-requirements-py312.txt" in dockerignore
    assert "--require-hashes" in dockerfile
    assert dockerfile.count("scripts/check_poetry_toolchain.py") >= 2
    assert "--active" in dockerfile
    assert "poetry check --lock" in dockerfile


def test_every_workflow_that_executes_poetry_uses_the_pinned_setup() -> None:
    offenders: list[str] = []
    for path in sorted([*WORKFLOWS.glob("*.yml"), *WORKFLOWS.glob("*.yaml")]):
        body = path.read_text(encoding="utf-8")
        executes_poetry = "poetry " in body.lower()
        assert "pipx install poetry" not in body.lower(), path.name
        if executes_poetry and "uses: ./.github/actions/setup-poetry" not in body:
            offenders.append(path.name)
    assert not offenders, f"workflows execute ambient Poetry: {offenders}"


def test_make_check_validates_the_committed_lock_without_regenerating() -> None:
    makefile = MAKEFILE.read_text(encoding="utf-8")
    assert "poetry-lock-check:" in makefile
    recipe = makefile.split("poetry-lock-check:", 1)[1].split("\n\n", 1)[0]
    assert "check_poetry_toolchain.py --active" in recipe
    assert "poetry check --lock" in recipe
    assert "poetry lock" not in recipe.replace("poetry check --lock", "")


def test_the_real_project_pin_is_exact_not_a_range() -> None:
    poetry = tomllib.loads(PYPROJECT.read_text(encoding="utf-8"))["tool"]["poetry"]
    assert poetry["requires-poetry"] == required_version(PYPROJECT.read_text())
